name: Build Geode Mod

on:
  workflow_dispatch:
  push:
    branches:
      - "**"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Windows
            os: windows-latest
            platform: win
          
          - name: macOS
            os: macos-latest
            platform: mac
          
          - name: iOS
            os: macos-latest
            platform: ios
          
          - name: Android32
            os: ubuntu-latest
            platform: android32
          
          - name: Android64
            os: ubuntu-latest
            platform: android64
    
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Setup Geode CLI
        uses: geode-sdk/cli@main
      
      - name: Install Geode SDK binaries
        run: geode sdk install-binaries
      
      - name: Build mod
        run: geode build -p ${{ matrix.config.platform }}
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.config.name }}-build
          path: build/*.geode
  
  package:
    name: Package builds
    runs-on: ubuntu-latest
    needs: ['build']
    
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      
      - name: Combine builds
        run: |
          mkdir -p combined
          find artifacts -name "*.geode" -exec cp {} combined/ \;
      
      - name: Upload combined artifact
        uses: actions/upload-artifact@v4
        with:
          name: Build Output
          path: combined/*.geode
